# Install the Nix/Apt packages (e.g. NodeJS, Yarn)
[phases.setup]
nixPkgs = ['nodejs']
nixpkgsArchive = 'e7c4226d1d92f33ad854d6da4f7e519e77690b8e73f93496881f8c539174d9df'

# Install the language/framework dependencies 
[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run prod:build",
  "npm run post:deployment"
]

[start]
cmd = "npm start"