export const PERMISSION_CODES = [
  "PRODUCTS_READ",
  "PRODUCTS_WRITE",
  "SALES_READ",
  "SALES_WRITE",
  "SALES_PAYMENTS",
  "SALES_DELETE",
  "STOCK_READ",
  "STOCK_WRITE",
  "CASH_READ",
  "CASH_WRITE",
  "CASH_RECONCILE",
  "EXPENSES_READ",
  "EXPENSES_WRITE",
  "CLIENTS_READ",
  "CLIENTS_WRITE",
  "SUPPLIERS_READ",
  "SUPPLIERS_WRITE",
  "SUPPLIER_DEBTS_WRITE",
  "PROCUREMENT_READ",
  "PROCUREMENT_WRITE",
  "PROCUREMENT_RECEIVE",
  "REPORTS_READ",
  "NOTIFICATIONS_READ",
] as const;

export type PermissionCode = (typeof PERMISSION_CODES)[number];

export const PERMISSION_LABELS: Record<PermissionCode, string> = {
  PRODUCTS_READ: "Consulter les produits",
  PRODUCTS_WRITE: "Modifier le catalogue",
  SALES_READ: "Consulter les ventes",
  SALES_WRITE: "Créer et modifier les ventes",
  SALES_PAYMENTS: "Enregistrer les paiements",
  SALES_DELETE: "Annuler les ventes",
  STOCK_READ: "Consulter le stock",
  STOCK_WRITE: "Modifier le stock",
  CASH_READ: "Consulter la caisse",
  CASH_WRITE: "Ouvrir, fermer et mouvementer la caisse",
  CASH_RECONCILE: "Rapprocher la caisse",
  EXPENSES_READ: "Consulter les dépenses",
  EXPENSES_WRITE: "Gérer les dépenses",
  CLIENTS_READ: "Consulter les clients",
  CLIENTS_WRITE: "Gérer les clients",
  SUPPLIERS_READ: "Consulter les fournisseurs",
  SUPPLIERS_WRITE: "Gérer les fournisseurs",
  SUPPLIER_DEBTS_WRITE: "Gérer les dettes fournisseurs",
  PROCUREMENT_READ: "Consulter les achats",
  PROCUREMENT_WRITE: "Créer et gérer les bons de commande",
  PROCUREMENT_RECEIVE: "Réceptionner les achats",
  REPORTS_READ: "Consulter les rapports et marges",
  NOTIFICATIONS_READ: "Consulter les notifications avancées",
};

export const EMPLOYEE_DEFAULT_PERMISSIONS = new Set<PermissionCode>([
  "PRODUCTS_READ",
  "SALES_READ",
  "SALES_WRITE",
  "SALES_PAYMENTS",
  "STOCK_READ",
  "STOCK_WRITE",
  "CASH_READ",
  "CASH_WRITE",
  "EXPENSES_READ",
  "CLIENTS_READ",
  "CLIENTS_WRITE",
  "SUPPLIERS_READ",
  "PROCUREMENT_READ",
  "REPORTS_READ",
  "NOTIFICATIONS_READ",
]);
